"""`huddle setup`: turn a Linux machine with Huddle installed into a node.

One idempotent pass, re-run to upgrade:

1. llama.cpp — upstream's own prebuilt release at the pin, checksum verified.
   No compiler, no headers: the build every node runs is byte-for-byte the
   same, which is exactly what the RPC version handshake demands.
2. The shared libraries it needs, from the distribution's packages.
3. A short config file, written only if there is none.
4. A systemd unit, so the node is back after every reboot.
5. Firewall rules for the local subnet. ufw on the real nodes silently drops
   new ports on the LAN, and the symptom is a timeout that looks exactly like
   a broken network.

Privileged steps go through ``sudo`` one command at a time, so a user without
passwordless sudo is asked once and nothing else runs as root. The logic is
pure functions over a small command runner, so it is testable without any of
it happening.
"""

from __future__ import annotations

import contextlib
import dataclasses
import grp
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tarfile
import time
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import httpx

from huddle import paths
from huddle.config import HuddleConfig
from huddle.pin import ARCHES, Pin, load_pin
from huddle.system import default_route_address, local_addresses, subnet_of

UNIT_NAME = "huddle.service"
UNIT_DIR = Path("/etc/systemd/system")
# Written into every unit we generate. A huddle.service without it predates
# `huddle setup` — installed by scripts/install-service.sh from a checkout —
# and is replaced rather than trusted.
UNIT_MARKER = "# Generated by `huddle setup`"
# Units from the checkout era that would fight the new one for its ports.
LEGACY_UNITS = ("huddle-agent.service",)

Echo = Callable[[str], None]
Firewall = Literal["ufw", "firewalld"]
Manager = Literal["apt", "dnf", "pacman"]

# Libraries the prebuilt release links against, and the package that provides
# each. Normally all present on a desktop install; the Vulkan loader is the one
# a minimal or server install lacks.
LIBRARY_PACKAGES: dict[str, dict[Manager, str]] = {
    "libvulkan.so.1": {"apt": "libvulkan1", "dnf": "vulkan-loader", "pacman": "vulkan-icd-loader"},
    "libgomp.so.1": {"apt": "libgomp1", "dnf": "libgomp", "pacman": "gcc-libs"},
    "libssl.so.3": {"apt": "libssl3", "dnf": "openssl-libs", "pacman": "openssl"},
    "libcrypto.so.3": {"apt": "libssl3", "dnf": "openssl-libs", "pacman": "openssl"},
    "libzstd.so.1": {"apt": "libzstd1", "dnf": "libzstd", "pacman": "zstd"},
    "libz.so.1": {"apt": "zlib1g", "dnf": "zlib", "pacman": "zlib"},
    "libstdc++.so.6": {"apt": "libstdc++6", "dnf": "libstdc++", "pacman": "gcc-libs"},
}


class SetupError(Exception):
    """A step that cannot continue, with a message meant for the user."""


# -- running commands ------------------------------------------------------------


class Runner:
    """Runs one-shot commands, with ``sudo`` for the privileged ones.

    These are short installer commands, not supervised processes: nothing here
    outlives the call, so the supervision helper in ``process.py`` would add
    nothing but ceremony.
    """

    def __init__(self) -> None:
        # Standard sudo discards piped input; SUDO_ASKPASS is how an unattended
        # install supplies a password.
        self.sudo = ["sudo", "-A"] if os.environ.get("SUDO_ASKPASS") else ["sudo"]

    def run(
        self,
        argv: Sequence[str],
        *,
        sudo: bool = False,
        input: str | None = None,
        check: bool = True,
    ) -> subprocess.CompletedProcess[str]:
        command = [*self.sudo, *argv] if sudo and os.geteuid() != 0 else list(argv)
        try:
            result = subprocess.run(
                command, input=input, text=True, capture_output=True, check=False
            )
        except OSError as exc:
            raise SetupError(f"could not run {command[0]}: {exc}") from exc
        if check and result.returncode != 0:
            lines = (result.stderr or result.stdout).strip().splitlines()
            detail = lines[-1] if lines else f"exit {result.returncode}"
            raise SetupError(f"`{' '.join(argv)}` failed: {detail}")
        return result


# -- llama.cpp ---------------------------------------------------------------------


def machine_arch(machine: str | None = None) -> str:
    """Upstream's name for this CPU architecture."""
    name = (machine or platform.machine()).lower()
    if name not in ARCHES:
        raise SetupError(
            f"no prebuilt llama.cpp for {name}; build it with scripts/bootstrap-node.sh "
            f"and set binaries.llama_server"
        )
    return ARCHES[name]


def download(
    url: str, dest: Path, sha256: str, *, echo: Echo, client: httpx.Client | None = None
) -> None:
    """Fetch ``url`` to ``dest``, refusing it unless its checksum matches."""
    digest = hashlib.sha256()
    http = client or httpx.Client(follow_redirects=True, timeout=httpx.Timeout(30.0, read=120.0))
    try:
        with http.stream("GET", url) as response:
            response.raise_for_status()
            total = int(response.headers.get("content-length") or 0)
            done, shown = 0, -1
            with dest.open("wb") as handle:
                for chunk in response.iter_bytes(1 << 20):
                    handle.write(chunk)
                    digest.update(chunk)
                    done += len(chunk)
                    percent = done * 100 // total if total else -1
                    if percent >= 0 and percent // 10 != shown // 10:
                        shown = percent
                        echo(f"    {percent:3d}%  {done / 2**20:.0f} of {total / 2**20:.0f} MB")
    except httpx.HTTPError as exc:
        dest.unlink(missing_ok=True)
        raise SetupError(f"download failed: {exc}") from exc
    finally:
        if client is None:
            http.close()
    if digest.hexdigest() != sha256:
        dest.unlink(missing_ok=True)
        raise SetupError(
            f"checksum mismatch for {url}: expected {sha256}, got {digest.hexdigest()}. "
            f"Nothing was installed."
        )


def extract_release(archive: Path, target: Path) -> None:
    """Unpack upstream's tarball into ``target``, replacing what was there.

    Upstream wraps everything in one ``llama-<tag>/`` directory; its contents
    are what ``target`` should hold. Extraction goes to a sibling first, so a
    failure halfway leaves the previous install intact.
    """
    staging = target.with_name(target.name + ".partial")
    shutil.rmtree(staging, ignore_errors=True)
    staging.mkdir(parents=True)
    try:
        with tarfile.open(archive) as tar:
            # The "data" filter refuses absolute paths, links out of the tree
            # and device files — a tarball must not be able to write elsewhere.
            tar.extractall(staging, filter="data")
        entries = list(staging.iterdir())
        root = entries[0] if len(entries) == 1 and entries[0].is_dir() else staging
        if not (root / "llama-server").is_file():
            raise SetupError(f"{archive.name} has no llama-server in it")
        shutil.rmtree(target, ignore_errors=True)
        root.rename(target)
    except (tarfile.TarError, OSError) as exc:
        raise SetupError(f"could not unpack {archive.name}: {exc}") from exc
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def build_matches(version: str, pin: Pin) -> bool:
    """Whether a ``--version`` line is the pinned commit (prefix-matched)."""
    from huddle.llamacpp import version_commit

    commit = version_commit(version)
    if not commit:
        return False
    return pin.ref.startswith(commit) or commit.startswith(pin.ref)


def install_llamacpp(
    pin: Pin,
    *,
    root: Path,
    arch: str,
    echo: Echo,
    fetch: Callable[[str, Path, str], None] | None = None,
) -> Path:
    """Install the pinned release under ``root`` and return its llama-server."""
    from huddle.llamacpp import LlamaCppError, binary_version

    if pin.release is None:
        raise SetupError("llamacpp.pin names no release to install")
    target = root / pin.release
    server = target / "llama-server"
    if server.is_file():
        with contextlib.suppress(LlamaCppError):
            if build_matches(binary_version(server), pin):
                echo(f"✓ llama.cpp {pin.release} already installed")
                return server

    digest = pin.digest(arch)
    if digest is None:
        raise SetupError(f"llamacpp.pin has no checksum for the {arch} build")
    root.mkdir(parents=True, exist_ok=True)
    archive = root / (pin.asset(arch) + ".download")
    echo(f"→ downloading llama.cpp {pin.release} ({pin.asset(arch)})")
    (fetch or (lambda url, dest, sha: download(url, dest, sha, echo=echo)))(
        pin.asset_url(arch), archive, digest
    )
    try:
        extract_release(archive, target)
    finally:
        archive.unlink(missing_ok=True)

    # Earlier releases are dead weight once this one is in place; a node only
    # ever runs the pinned build.
    for other in root.iterdir():
        if other.is_dir() and other != target:
            shutil.rmtree(other, ignore_errors=True)
    echo(f"✓ llama.cpp {pin.release} installed in {target}")
    return server


def missing_libraries(ldd_output: str) -> set[str]:
    """Sonames ``ldd`` could not resolve."""
    missing: set[str] = set()
    for line in ldd_output.splitlines():
        name, arrow, where = line.strip().partition("=>")
        if arrow and where.strip() == "not found":
            missing.add(name.strip())
    return missing


def package_manager() -> Manager | None:
    candidates: tuple[tuple[Manager, str], ...] = (
        ("apt", "apt-get"),
        ("dnf", "dnf"),
        ("pacman", "pacman"),
    )
    for manager, binary in candidates:
        if shutil.which(binary):
            return manager
    return None


def packages_for(missing: set[str], manager: Manager) -> tuple[list[str], list[str]]:
    """Packages providing ``missing``, and any sonames nothing is known to provide."""
    packages: list[str] = []
    unknown: list[str] = []
    for soname in sorted(missing):
        package = LIBRARY_PACKAGES.get(soname, {}).get(manager)
        if package is None:
            unknown.append(soname)
        elif package not in packages:
            packages.append(package)
    return packages, unknown


def install_command(manager: Manager, packages: list[str]) -> list[str]:
    return {
        "apt": ["apt-get", "install", "-y", *packages],
        "dnf": ["dnf", "install", "-y", *packages],
        "pacman": ["pacman", "-S", "--needed", "--noconfirm", *packages],
    }[manager]


def ensure_libraries(install_dir: Path, runner: Runner, echo: Echo) -> None:
    """Install whatever shared libraries the release cannot find."""
    if shutil.which("ldd") is None:
        return
    binaries = [
        p
        for p in install_dir.iterdir()
        if p.suffix == ".so" or p.name in ("llama-server", *paths.RPC_SERVER_NAMES)
    ]
    missing: set[str] = set()
    for binary in binaries:
        result = runner.run(["ldd", str(binary)], check=False)
        missing |= missing_libraries(result.stdout)
    if not missing:
        echo("✓ shared libraries present")
        return

    manager = package_manager()
    if manager is None:
        raise SetupError(f"missing libraries {', '.join(sorted(missing))}; install them first")
    packages, unknown = packages_for(missing, manager)
    if unknown:
        raise SetupError(f"missing libraries with no known package: {', '.join(unknown)}")
    echo(f"→ installing {' '.join(packages)} (needs sudo)")
    if manager == "apt":
        runner.run(["apt-get", "update", "-q"], sudo=True, check=False)
    runner.run(install_command(manager, packages), sudo=True)
    echo("✓ shared libraries installed")


def report_devices(server: Path, echo: Echo) -> None:
    """Say what llama.cpp can see, and what to do if it sees no GPU."""
    from huddle.llamacpp import LlamaCppError, list_devices

    try:
        devices = list_devices(server)
    except LlamaCppError as exc:
        raise SetupError(f"llama-server does not run: {exc}") from exc
    if devices:
        for device in devices:
            memory = f" ({device.total_mib} MiB)" if device.total_mib else ""
            echo(f"✓ {device.id}: {device.name}{memory}")
        return
    echo("! llama.cpp sees no GPU, so this node will run models on CPU only")
    if shutil.which("nvidia-smi"):
        echo("  the NVIDIA driver is installed but Vulkan cannot see it; install its Vulkan")
        echo("  support (Ubuntu: the libnvidia-gl package matching the driver version)")
    else:
        echo("  install your GPU's Vulkan driver (Ubuntu: mesa-vulkan-drivers for AMD/Intel,")
        echo("  or the NVIDIA driver), then re-run `huddle setup`")


# -- config --------------------------------------------------------------------------


def config_text(*, cluster: str, models_dir: Path) -> str:
    return (
        "# Huddle node settings. Every key has a default; huddle.example.yaml in the\n"
        "# repository lists them all. Re-run `huddle setup` after editing.\n"
        "\n"
        "discovery:\n"
        "  # PCs on this network with the same cluster name join each other.\n"
        f"  cluster: {json.dumps(cluster)}\n"
        "\n"
        "models:\n"
        "  # Where downloaded GGUF files are kept.\n"
        f"  dir: {json.dumps(str(models_dir))}\n"
    )


def write_config(path: Path, *, cluster: str, models_dir: Path, echo: Echo) -> None:
    if path.exists():
        echo(f"✓ keeping existing config {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config_text(cluster=cluster, models_dir=models_dir))
    echo(f"✓ wrote {path}")


# -- the service -----------------------------------------------------------------------


def huddle_executable() -> Path:
    """The `huddle` command of the environment running this, for ExecStart.

    Beside the interpreter first: for a `uv tool` install that is the tool's
    own environment, which is what should run, not whatever PATH finds first.
    """
    beside = Path(sys.executable).parent / "huddle"
    if beside.is_file():
        return beside
    found = shutil.which("huddle")
    if found:
        return Path(found)
    raise SetupError("cannot find the huddle command to run as a service")


def existing_groups(names: Sequence[str]) -> list[str]:
    groups: list[str] = []
    for name in names:
        try:
            grp.getgrnam(name)
        except KeyError:
            continue
        groups.append(name)
    return groups


def unit_text(
    *,
    user: str,
    home: Path,
    executable: Path,
    config: Path,
    groups: Sequence[str] = (),
) -> str:
    lines = [
        f"{UNIT_MARKER}. Re-run it to update; `huddle uninstall` removes it.",
        "[Unit]",
        "Description=Huddle: pooled LLM inference across the machines on this network",
        "Documentation=https://github.com/sszxt/huddle",
        "After=network-online.target",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=exec",
        f"User={user}",
        f"WorkingDirectory={home}",
        f"Environment=HUDDLE_CONFIG={config}",
        f"Environment=PATH={executable.parent}:/usr/local/bin:/usr/bin:/bin",
        f"ExecStart={executable} serve",
        "Restart=on-failure",
        "RestartSec=5",
        "# 143 is SIGTERM's exit status: a stop we asked for, not a failure.",
        "SuccessExitStatus=143",
        "# llama.cpp runs as a child; signalling only the parent would leave it",
        "# holding its port and its GPU memory.",
        "KillMode=control-group",
        "TimeoutStopSec=90",
    ]
    if groups:
        # Render nodes for AMD and Intel GPUs belong to these groups; without a
        # desktop session nothing else grants the service access to them.
        lines.append(f"SupplementaryGroups={' '.join(groups)}")
    lines += ["", "[Install]", "WantedBy=multi-user.target", ""]
    return "\n".join(lines)


def install_service(unit: str, runner: Runner, echo: Echo, *, unit_dir: Path = UNIT_DIR) -> None:
    for legacy in LEGACY_UNITS:
        if (unit_dir / legacy).exists():
            echo(f"→ replacing the old {legacy} from a checkout install")
            runner.run(["systemctl", "disable", "--now", legacy], sudo=True, check=False)
            runner.run(["rm", "-f", str(unit_dir / legacy)], sudo=True)

    path = unit_dir / UNIT_NAME
    with contextlib.suppress(OSError):
        if path.exists() and UNIT_MARKER not in path.read_text():
            echo(f"→ replacing the old {UNIT_NAME} from a checkout install")
            runner.run(["systemctl", "stop", UNIT_NAME], sudo=True, check=False)

    runner.run(["tee", str(path)], sudo=True, input=unit)
    runner.run(["systemctl", "daemon-reload"], sudo=True)
    runner.run(["systemctl", "enable", UNIT_NAME], sudo=True)
    # Restart, not start: re-running setup is how a node upgrades, and the new
    # code only takes effect in a new process.
    runner.run(["systemctl", "restart", UNIT_NAME], sudo=True)
    echo(f"✓ {UNIT_NAME} installed, enabled and started")


def wait_for_api(port: int, *, timeout: float = 30.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        with contextlib.suppress(httpx.HTTPError):
            if httpx.get(f"http://127.0.0.1:{port}/health", timeout=2.0).status_code == 200:
                return True
        time.sleep(0.5)
    return False


# -- firewall -------------------------------------------------------------------------


def detect_firewall(runner: Runner) -> Firewall | None:
    """The firewall that is actually filtering, if any."""
    if shutil.which("ufw"):
        status = runner.run(["ufw", "status"], sudo=True, check=False).stdout
        if "Status: active" in status:
            return "ufw"
    if shutil.which("firewall-cmd"):
        state = runner.run(["firewall-cmd", "--state"], sudo=True, check=False).stdout
        if state.strip() == "running":
            return "firewalld"
    return None


def firewall_commands(
    firewall: Firewall, subnet: str, ports: Sequence[int], *, remove: bool = False
) -> list[list[str]]:
    """Commands that open (or close) ``ports`` to ``subnet`` only.

    Only the local subnet: the RPC port has no authentication and no
    encryption, and upstream says never to expose it.
    """
    if firewall == "ufw":
        verb = ["delete", "allow"] if remove else ["allow"]
        return [
            ["ufw", *verb, "from", subnet, "to", "any", "port", str(port), "proto", "tcp"]
            + ([] if remove else ["comment", "huddle"])
            for port in ports
        ]
    action = "--remove-rich-rule" if remove else "--add-rich-rule"
    return [
        [
            "firewall-cmd",
            "--permanent",
            f'{action}=rule family="ipv4" source address="{subnet}" '
            f'port port="{port}" protocol="tcp" accept',
        ]
        for port in ports
    ] + [["firewall-cmd", "--reload"]]


def local_subnet() -> str | None:
    address = default_route_address()
    return subnet_of(address, local_addresses()) if address else None


# -- what setup did, for uninstall -------------------------------------------------------


@dataclass
class Installed:
    """What setup changed outside the user's own directories."""

    service: bool = False
    firewall: Firewall | None = None
    subnet: str | None = None
    ports: list[int] = field(default_factory=list)

    @classmethod
    def load(cls, path: Path) -> Installed:
        try:
            raw = json.loads(path.read_text())
        except (OSError, ValueError):
            return cls()
        return cls(
            service=bool(raw.get("service")),
            firewall=raw.get("firewall"),
            subnet=raw.get("subnet"),
            ports=[int(p) for p in raw.get("ports", [])],
        )

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(dataclasses.asdict(self), indent=2) + "\n")


def record_file() -> Path:
    return paths.state_dir() / "setup.json"


# -- the whole thing --------------------------------------------------------------------


def run_setup(
    *,
    cluster: str | None,
    models_dir: Path | None,
    service: bool,
    firewall: bool,
    echo: Echo,
    runner: Runner | None = None,
) -> None:
    if os.geteuid() == 0:
        raise SetupError(
            "run `huddle setup` as your own user, not root; it asks for sudo when it needs to"
        )
    runner = runner or Runner()
    pin = load_pin()
    if pin is None:
        raise SetupError("llamacpp.pin is missing from this install of Huddle")

    server = install_llamacpp(pin, root=paths.llamacpp_root(), arch=machine_arch(), echo=echo)
    ensure_libraries(server.parent, runner, echo)
    report_devices(server, echo)

    config_file = paths.default_config_file()
    write_config(
        config_file,
        cluster=cluster or "default",
        models_dir=models_dir or paths.default_models_dir(),
        echo=echo,
    )
    config = HuddleConfig.load(config_file)
    config.models.dir.mkdir(parents=True, exist_ok=True)

    record = Installed.load(record_file())
    if firewall:
        kind = detect_firewall(runner)
        subnet = local_subnet()
        ports = [config.api.port, config.rpc.port]
        if kind is None:
            echo("✓ no active firewall to configure")
        elif subnet is None:
            echo(f"! {kind} is active but this machine's subnet is unknown; open ports")
            echo(f"  {', '.join(map(str, ports))}/tcp to your LAN yourself")
        else:
            if record.firewall and record.subnet and record.subnet != subnet:
                # The network changed since the last run: close what was opened
                # to the old one rather than leave it open forever.
                for command in firewall_commands(
                    record.firewall, record.subnet, record.ports, remove=True
                ):
                    runner.run(command, sudo=True, check=False)
            for command in firewall_commands(kind, subnet, ports):
                runner.run(command, sudo=True)
            record.firewall, record.subnet, record.ports = kind, subnet, ports
            echo(f"✓ {kind}: opened {', '.join(map(str, ports))}/tcp to {subnet}")

    if service:
        if shutil.which("systemctl") is None:
            echo("! no systemd here: start Huddle yourself with `huddle serve`")
        else:
            unit = unit_text(
                user=os.environ.get("USER") or Path.home().name,
                home=Path.home(),
                executable=huddle_executable(),
                config=config_file,
                groups=existing_groups(("render", "video")),
            )
            install_service(unit, runner, echo)
            record.service = True
    record.save(record_file())

    if service and record.service:
        if wait_for_api(config.api.port):
            echo("")
            echo(f"✓ Huddle is running → http://localhost:{config.api.port}")
        else:
            echo(f"! the service started but its API is not answering on :{config.api.port};")
            echo("  see `journalctl -u huddle -e`")
    else:
        echo("")
        echo("✓ set up. Start it with `huddle serve`")


def run_uninstall(*, purge: bool, echo: Echo, runner: Runner | None = None) -> None:
    runner = runner or Runner()
    record = Installed.load(record_file())
    unit = UNIT_DIR / UNIT_NAME
    if unit.exists():
        runner.run(["systemctl", "disable", "--now", UNIT_NAME], sudo=True, check=False)
        runner.run(["rm", "-f", str(unit)], sudo=True)
        runner.run(["systemctl", "daemon-reload"], sudo=True, check=False)
        echo(f"✓ removed {UNIT_NAME}")
    if record.firewall and record.subnet and record.ports:
        for command in firewall_commands(record.firewall, record.subnet, record.ports, remove=True):
            runner.run(command, sudo=True, check=False)
        echo(f"✓ closed {', '.join(map(str, record.ports))}/tcp in {record.firewall}")
    shutil.rmtree(paths.llamacpp_root(), ignore_errors=True)
    echo("✓ removed llama.cpp")
    record_file().unlink(missing_ok=True)
    if purge:
        for directory in (paths.default_models_dir(), paths.config_dir(), paths.state_dir()):
            shutil.rmtree(directory, ignore_errors=True)
        echo("✓ removed models, config and node identity")
    else:
        echo(f"  kept your models in {paths.default_models_dir()} (use --purge to remove them)")
    echo("  remove the command itself with: uv tool uninstall huddle")


__all__ = [
    "Installed",
    "Runner",
    "SetupError",
    "build_matches",
    "config_text",
    "extract_release",
    "firewall_commands",
    "install_llamacpp",
    "install_service",
    "machine_arch",
    "missing_libraries",
    "packages_for",
    "run_setup",
    "run_uninstall",
    "unit_text",
]
